# Generated by Django 4.2.3 on 2023-08-08 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["title"],
                "permissions": (("modify_course", "Can modify course content"),),
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["course"],
                "permissions": (("modify_lesson", "Can modify lesson content"),),
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AlterModelOptions(
            name="tracking",
            options={
                "ordering": ["-user"],
                "verbose_name": "Активные уроки",
                "verbose_name_plural": "Активные уроки",
            },
        ),
    ]
