# Generated by Django 4.2.3 on 2023-08-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=250, unique_for_year='send_date', verbose_name='Текст отзыва'),
        ),
    ]
