# Generated by Django 4.2.3 on 2023-08-16 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0004_alter_review_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.AddField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(db_table='course_authors', related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Автор курса'),
        ),
    ]
